#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 71
#define ALIAS_COUNT 0
#define TOKEN_COUNT 48
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 5

enum {
  sym_null = 1,
  sym_true = 2,
  sym_false = 3,
  sym_self = 4,
  sym_outer = 5,
  sym_id = 6,
  anon_sym_DQUOTE = 7,
  aux_sym__string_inner_token1 = 8,
  sym_escape_sequence = 9,
  sym_number = 10,
  anon_sym_LBRACE = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym_hsep = 16,
  anon_sym_import = 17,
  anon_sym_importstr = 18,
  anon_sym_importbin = 19,
  anon_sym_local = 20,
  anon_sym_SEMI = 21,
  anon_sym_EQ = 22,
  anon_sym_function = 23,
  anon_sym_LPAREN = 24,
  anon_sym_RPAREN = 25,
  anon_sym_DOT = 26,
  anon_sym_PLUS = 27,
  anon_sym_DASH = 28,
  anon_sym_BANG = 29,
  anon_sym_TILDE = 30,
  anon_sym_STAR = 31,
  anon_sym_SLASH = 32,
  anon_sym_PERCENT = 33,
  anon_sym_LT_LT = 34,
  anon_sym_GT_GT = 35,
  anon_sym_LT = 36,
  anon_sym_GT = 37,
  anon_sym_LT_EQ = 38,
  anon_sym_GT_EQ = 39,
  anon_sym_in = 40,
  anon_sym_EQ_EQ = 41,
  anon_sym_BANG_EQ = 42,
  anon_sym_AMP = 43,
  anon_sym_CARET = 44,
  anon_sym_PIPE = 45,
  anon_sym_AMP_AMP = 46,
  anon_sym_PIPE_PIPE = 47,
  sym_source_file = 48,
  sym_expr = 49,
  sym__expr = 50,
  sym_string = 51,
  aux_sym__string_inner = 52,
  sym_object = 53,
  sym_member = 54,
  sym_field = 55,
  sym_fieldname = 56,
  sym_value = 57,
  sym_array = 58,
  sym_import = 59,
  sym_bindexpr = 60,
  sym_bind = 61,
  sym_functiondef = 62,
  sym_param = 63,
  sym_index = 64,
  sym_unary_expr = 65,
  sym_binary_expr = 66,
  aux_sym_object_repeat1 = 67,
  aux_sym_array_repeat1 = 68,
  aux_sym_bindexpr_repeat1 = 69,
  aux_sym_functiondef_repeat1 = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_null] = "null",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_self] = "self",
  [sym_outer] = "outer",
  [sym_id] = "id",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_inner_token1] = "_string_inner_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_hsep] = "hsep",
  [anon_sym_import] = "import",
  [anon_sym_importstr] = "importstr",
  [anon_sym_importbin] = "importbin",
  [anon_sym_local] = "local",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT] = ".",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_TILDE] = "~",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_in] = "in",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_AMP] = "&",
  [anon_sym_CARET] = "^",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym__expr] = "_expr",
  [sym_string] = "string",
  [aux_sym__string_inner] = "_string_inner",
  [sym_object] = "object",
  [sym_member] = "member",
  [sym_field] = "field",
  [sym_fieldname] = "fieldname",
  [sym_value] = "value",
  [sym_array] = "array",
  [sym_import] = "import",
  [sym_bindexpr] = "bindexpr",
  [sym_bind] = "bind",
  [sym_functiondef] = "functiondef",
  [sym_param] = "param",
  [sym_index] = "index",
  [sym_unary_expr] = "unary_expr",
  [sym_binary_expr] = "binary_expr",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_bindexpr_repeat1] = "bindexpr_repeat1",
  [aux_sym_functiondef_repeat1] = "functiondef_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_null] = sym_null,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_self] = sym_self,
  [sym_outer] = sym_outer,
  [sym_id] = sym_id,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_inner_token1] = aux_sym__string_inner_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_hsep] = sym_hsep,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_importstr] = anon_sym_importstr,
  [anon_sym_importbin] = anon_sym_importbin,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym__expr] = sym__expr,
  [sym_string] = sym_string,
  [aux_sym__string_inner] = aux_sym__string_inner,
  [sym_object] = sym_object,
  [sym_member] = sym_member,
  [sym_field] = sym_field,
  [sym_fieldname] = sym_fieldname,
  [sym_value] = sym_value,
  [sym_array] = sym_array,
  [sym_import] = sym_import,
  [sym_bindexpr] = sym_bindexpr,
  [sym_bind] = sym_bind,
  [sym_functiondef] = sym_functiondef,
  [sym_param] = sym_param,
  [sym_index] = sym_index,
  [sym_unary_expr] = sym_unary_expr,
  [sym_binary_expr] = sym_binary_expr,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_bindexpr_repeat1] = aux_sym_bindexpr_repeat1,
  [aux_sym_functiondef_repeat1] = aux_sym_functiondef_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_self] = {
    .visible = true,
    .named = true,
  },
  [sym_outer] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_inner_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_hsep] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_importstr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_importbin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_inner] = {
    .visible = false,
    .named = false,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_member] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fieldname] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_bindexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_bind] = {
    .visible = true,
    .named = true,
  },
  [sym_functiondef] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bindexpr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_functiondef_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_op = 2,
  field_params = 3,
  field_right = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_op] = "op",
  [field_params] = "params",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [3] =
    {field_params, 2},
  [4] =
    {field_params, 2},
    {field_params, 3},
  [6] =
    {field_params, 2},
    {field_params, 3},
    {field_params, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(46);
      if (lookahead == '!') ADVANCE(83);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '$') ADVANCE(51);
      if (lookahead == '%') ADVANCE(87);
      if (lookahead == '&') ADVANCE(97);
      if (lookahead == '(') ADVANCE(77);
      if (lookahead == ')') ADVANCE(78);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '+') ADVANCE(80);
      if (lookahead == ',') ADVANCE(62);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '.') ADVANCE(79);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == '0') ADVANCE(57);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ';') ADVANCE(73);
      if (lookahead == '<') ADVANCE(90);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead == '>') ADVANCE(91);
      if (lookahead == '[') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead == ']') ADVANCE(65);
      if (lookahead == '^') ADVANCE(98);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == '{') ADVANCE(61);
      if (lookahead == '|') ADVANCE(99);
      if (lookahead == '}') ADVANCE(63);
      if (lookahead == '~') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(44)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4)
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(82);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '$') ADVANCE(51);
      if (lookahead == ')') ADVANCE(78);
      if (lookahead == '+') ADVANCE(80);
      if (lookahead == ',') ADVANCE(62);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '0') ADVANCE(57);
      if (lookahead == '=') ADVANCE(74);
      if (lookahead == '[') ADVANCE(64);
      if (lookahead == ']') ADVANCE(65);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == '{') ADVANCE(61);
      if (lookahead == '~') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == ')') ADVANCE(78);
      if (lookahead == '[') ADVANCE(64);
      if (lookahead == '}') ADVANCE(63);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(96);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(50);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(72);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(31);
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 41:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 42:
      if (lookahead == '"' ||
          lookahead == '/' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 44:
      if (eof) ADVANCE(46);
      if (lookahead == '!') ADVANCE(83);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '$') ADVANCE(51);
      if (lookahead == '%') ADVANCE(87);
      if (lookahead == '&') ADVANCE(97);
      if (lookahead == '(') ADVANCE(77);
      if (lookahead == ')') ADVANCE(78);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '+') ADVANCE(80);
      if (lookahead == ',') ADVANCE(62);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '.') ADVANCE(79);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == '0') ADVANCE(57);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ';') ADVANCE(73);
      if (lookahead == '<') ADVANCE(90);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead == '>') ADVANCE(91);
      if (lookahead == '[') ADVANCE(64);
      if (lookahead == ']') ADVANCE(65);
      if (lookahead == '^') ADVANCE(98);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == '{') ADVANCE(61);
      if (lookahead == '|') ADVANCE(99);
      if (lookahead == '}') ADVANCE(63);
      if (lookahead == '~') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(44)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 45:
      if (eof) ADVANCE(46);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '%') ADVANCE(87);
      if (lookahead == '&') ADVANCE(97);
      if (lookahead == ')') ADVANCE(78);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '+') ADVANCE(80);
      if (lookahead == ',') ADVANCE(62);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '.') ADVANCE(79);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == ':') ADVANCE(68);
      if (lookahead == ';') ADVANCE(73);
      if (lookahead == '<') ADVANCE(90);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(91);
      if (lookahead == ']') ADVANCE(65);
      if (lookahead == '^') ADVANCE(98);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == '|') ADVANCE(99);
      if (lookahead == '}') ADVANCE(63);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(45)
      END_STATE();
    case 46:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_self);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_outer);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym__string_inner_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym__string_inner_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(59);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(59);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_hsep);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_hsep);
      if (lookahead == ':') ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_hsep);
      if (lookahead == ':') ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_import);
      if (lookahead == 'b') ADVANCE(16);
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_importstr);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_importbin);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(96);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(88);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(93);
      if (lookahead == '>') ADVANCE(89);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(101);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 45},
  [28] = {.lex_state = 45},
  [29] = {.lex_state = 45},
  [30] = {.lex_state = 45},
  [31] = {.lex_state = 45},
  [32] = {.lex_state = 45},
  [33] = {.lex_state = 45},
  [34] = {.lex_state = 45},
  [35] = {.lex_state = 45},
  [36] = {.lex_state = 45},
  [37] = {.lex_state = 45},
  [38] = {.lex_state = 45},
  [39] = {.lex_state = 45},
  [40] = {.lex_state = 45},
  [41] = {.lex_state = 45},
  [42] = {.lex_state = 45},
  [43] = {.lex_state = 45},
  [44] = {.lex_state = 45},
  [45] = {.lex_state = 45},
  [46] = {.lex_state = 45},
  [47] = {.lex_state = 45},
  [48] = {.lex_state = 45},
  [49] = {.lex_state = 45},
  [50] = {.lex_state = 45},
  [51] = {.lex_state = 45},
  [52] = {.lex_state = 45},
  [53] = {.lex_state = 45},
  [54] = {.lex_state = 45},
  [55] = {.lex_state = 45},
  [56] = {.lex_state = 45},
  [57] = {.lex_state = 45},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_self] = ACTIONS(1),
    [sym_outer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_hsep] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_importstr] = ACTIONS(1),
    [anon_sym_importbin] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(95),
    [sym_expr] = STATE(84),
    [sym__expr] = STATE(50),
    [sym_string] = STATE(50),
    [sym_object] = STATE(50),
    [sym_array] = STATE(50),
    [sym_import] = STATE(50),
    [sym_bindexpr] = STATE(50),
    [sym_functiondef] = STATE(50),
    [sym_index] = STATE(50),
    [sym_unary_expr] = STATE(50),
    [sym_binary_expr] = STATE(50),
    [sym_null] = ACTIONS(3),
    [sym_true] = ACTIONS(3),
    [sym_false] = ACTIONS(3),
    [sym_self] = ACTIONS(3),
    [sym_outer] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(5),
    [sym_number] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [anon_sym_importstr] = ACTIONS(13),
    [anon_sym_importbin] = ACTIONS(13),
    [anon_sym_local] = ACTIONS(15),
    [anon_sym_function] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_BANG] = ACTIONS(19),
    [anon_sym_TILDE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    ACTIONS(21), 1,
      anon_sym_RBRACK,
    STATE(75), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [55] = 12,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(91), 1,
      sym_value,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(23), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(57), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [110] = 12,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    STATE(75), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [165] = 12,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [220] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(49), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [272] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(29), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(35), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [324] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(37), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [376] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(79), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [428] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(31), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(41), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [480] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(38), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [532] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(33), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [584] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(44), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [636] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(33), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(54), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [688] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(35), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(53), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [740] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(85), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [792] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(37), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(52), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [844] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(39), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(51), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [896] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(41), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(45), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [948] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(43), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(43), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1000] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(45), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(40), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1052] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(75), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1104] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(47), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(32), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1156] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(99), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(49), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(48), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1208] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(78), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1260] = 11,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(15), 1,
      anon_sym_local,
    ACTIONS(17), 1,
      anon_sym_function,
    STATE(31), 1,
      sym_expr,
    ACTIONS(13), 2,
      anon_sym_importstr,
      anon_sym_importbin,
    ACTIONS(19), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_TILDE,
    ACTIONS(3), 6,
      sym_null,
      sym_true,
      sym_false,
      sym_self,
      sym_outer,
      sym_number,
    STATE(50), 10,
      sym__expr,
      sym_string,
      sym_object,
      sym_array,
      sym_import,
      sym_bindexpr,
      sym_functiondef,
      sym_index,
      sym_unary_expr,
      sym_binary_expr,
  [1312] = 2,
    ACTIONS(53), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(51), 23,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_hsep,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1344] = 2,
    ACTIONS(57), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(55), 23,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_hsep,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1376] = 2,
    ACTIONS(61), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(59), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1407] = 2,
    ACTIONS(65), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(63), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1438] = 3,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(71), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(67), 21,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1471] = 10,
    ACTIONS(87), 1,
      anon_sym_AMP,
    ACTIONS(89), 1,
      anon_sym_CARET,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1518] = 3,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(95), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(93), 21,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1551] = 2,
    ACTIONS(99), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(97), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1582] = 10,
    ACTIONS(87), 1,
      anon_sym_AMP,
    ACTIONS(89), 1,
      anon_sym_CARET,
    ACTIONS(101), 1,
      anon_sym_PIPE,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1629] = 2,
    ACTIONS(105), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(103), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1660] = 3,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(109), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(107), 21,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1693] = 3,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(113), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(111), 21,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1726] = 2,
    ACTIONS(117), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(115), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1757] = 9,
    ACTIONS(87), 1,
      anon_sym_AMP,
    ACTIONS(101), 1,
      anon_sym_PIPE,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1802] = 2,
    ACTIONS(121), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(119), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1833] = 2,
    ACTIONS(125), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(123), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1864] = 8,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(101), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1907] = 3,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(129), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(127), 21,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1940] = 7,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 2,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(73), 12,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1981] = 2,
    ACTIONS(133), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(131), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2012] = 2,
    ACTIONS(137), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(135), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2043] = 11,
    ACTIONS(87), 1,
      anon_sym_AMP,
    ACTIONS(89), 1,
      anon_sym_CARET,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    ACTIONS(139), 1,
      anon_sym_AMP_AMP,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(73), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PIPE_PIPE,
  [2092] = 3,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(143), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(141), 21,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2125] = 12,
    ACTIONS(87), 1,
      anon_sym_AMP,
    ACTIONS(89), 1,
      anon_sym_CARET,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    ACTIONS(139), 1,
      anon_sym_AMP_AMP,
    ACTIONS(147), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
    ACTIONS(145), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
  [2176] = 5,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(101), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(73), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2213] = 4,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(101), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(73), 17,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2248] = 2,
    ACTIONS(101), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(73), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2279] = 3,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(101), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(73), 19,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2312] = 2,
    ACTIONS(151), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(149), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2343] = 2,
    ACTIONS(155), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
    ACTIONS(153), 22,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [2374] = 13,
    ACTIONS(87), 1,
      anon_sym_AMP,
    ACTIONS(89), 1,
      anon_sym_CARET,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    ACTIONS(139), 1,
      anon_sym_AMP_AMP,
    ACTIONS(145), 1,
      anon_sym_DOT,
    ACTIONS(147), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(75), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(79), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(81), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(157), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(77), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(83), 3,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_in,
  [2423] = 8,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      sym_id,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    STATE(92), 1,
      sym_member,
    STATE(94), 1,
      sym_field,
    STATE(100), 1,
      sym_string,
    STATE(102), 1,
      sym_fieldname,
  [2448] = 8,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      sym_id,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_member,
    STATE(94), 1,
      sym_field,
    STATE(100), 1,
      sym_string,
    STATE(102), 1,
      sym_fieldname,
  [2473] = 8,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      sym_id,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      sym_member,
    STATE(94), 1,
      sym_field,
    STATE(100), 1,
      sym_string,
    STATE(102), 1,
      sym_fieldname,
  [2498] = 7,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      sym_id,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    STATE(92), 1,
      sym_member,
    STATE(94), 1,
      sym_field,
    STATE(100), 1,
      sym_string,
    STATE(102), 1,
      sym_fieldname,
  [2520] = 3,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym__string_inner,
    ACTIONS(171), 2,
      aux_sym__string_inner_token1,
      sym_escape_sequence,
  [2531] = 3,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym__string_inner,
    ACTIONS(175), 2,
      aux_sym__string_inner_token1,
      sym_escape_sequence,
  [2542] = 3,
    ACTIONS(177), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym__string_inner,
    ACTIONS(179), 2,
      aux_sym__string_inner_token1,
      sym_escape_sequence,
  [2553] = 4,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACK,
    STATE(83), 1,
      aux_sym_array_repeat1,
  [2566] = 3,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_object_repeat1,
  [2576] = 3,
    ACTIONS(188), 1,
      sym_id,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_param,
  [2586] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_object_repeat1,
  [2596] = 3,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_functiondef_repeat1,
  [2606] = 3,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_functiondef_repeat1,
  [2616] = 3,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_object_repeat1,
  [2626] = 3,
    ACTIONS(188), 1,
      sym_id,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      sym_param,
  [2636] = 3,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_SEMI,
    STATE(76), 1,
      aux_sym_bindexpr_repeat1,
  [2646] = 2,
    ACTIONS(218), 1,
      anon_sym_EQ,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2654] = 2,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(220), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2662] = 3,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      aux_sym_bindexpr_repeat1,
  [2672] = 3,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_array_repeat1,
  [2682] = 2,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(227), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [2690] = 2,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(229), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2698] = 3,
    ACTIONS(188), 1,
      sym_id,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_param,
  [2708] = 3,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_functiondef_repeat1,
  [2718] = 3,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      aux_sym_bindexpr_repeat1,
  [2728] = 3,
    ACTIONS(25), 1,
      anon_sym_RBRACK,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_array_repeat1,
  [2738] = 2,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [2745] = 2,
    ACTIONS(69), 1,
      anon_sym_DOT,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
  [2752] = 2,
    ACTIONS(246), 1,
      sym_id,
    STATE(73), 1,
      sym_bind,
  [2759] = 2,
    ACTIONS(246), 1,
      sym_id,
    STATE(88), 1,
      sym_bind,
  [2766] = 1,
    ACTIONS(238), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [2771] = 2,
    ACTIONS(5), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_string,
  [2778] = 1,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2783] = 1,
    ACTIONS(248), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2788] = 1,
    ACTIONS(208), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2793] = 2,
    ACTIONS(188), 1,
      sym_id,
    STATE(90), 1,
      sym_param,
  [2800] = 1,
    ACTIONS(250), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2805] = 1,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
  [2809] = 1,
    ACTIONS(254), 1,
      sym_hsep,
  [2813] = 1,
    ACTIONS(256), 1,
      anon_sym_LPAREN,
  [2817] = 1,
    ACTIONS(258), 1,
      sym_id,
  [2821] = 1,
    ACTIONS(69), 1,
      anon_sym_DOT,
  [2825] = 1,
    ACTIONS(260), 1,
      sym_hsep,
  [2829] = 1,
    ACTIONS(262), 1,
      anon_sym_EQ,
  [2833] = 1,
    ACTIONS(264), 1,
      sym_hsep,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 55,
  [SMALL_STATE(4)] = 110,
  [SMALL_STATE(5)] = 165,
  [SMALL_STATE(6)] = 220,
  [SMALL_STATE(7)] = 272,
  [SMALL_STATE(8)] = 324,
  [SMALL_STATE(9)] = 376,
  [SMALL_STATE(10)] = 428,
  [SMALL_STATE(11)] = 480,
  [SMALL_STATE(12)] = 532,
  [SMALL_STATE(13)] = 584,
  [SMALL_STATE(14)] = 636,
  [SMALL_STATE(15)] = 688,
  [SMALL_STATE(16)] = 740,
  [SMALL_STATE(17)] = 792,
  [SMALL_STATE(18)] = 844,
  [SMALL_STATE(19)] = 896,
  [SMALL_STATE(20)] = 948,
  [SMALL_STATE(21)] = 1000,
  [SMALL_STATE(22)] = 1052,
  [SMALL_STATE(23)] = 1104,
  [SMALL_STATE(24)] = 1156,
  [SMALL_STATE(25)] = 1208,
  [SMALL_STATE(26)] = 1260,
  [SMALL_STATE(27)] = 1312,
  [SMALL_STATE(28)] = 1344,
  [SMALL_STATE(29)] = 1376,
  [SMALL_STATE(30)] = 1407,
  [SMALL_STATE(31)] = 1438,
  [SMALL_STATE(32)] = 1471,
  [SMALL_STATE(33)] = 1518,
  [SMALL_STATE(34)] = 1551,
  [SMALL_STATE(35)] = 1582,
  [SMALL_STATE(36)] = 1629,
  [SMALL_STATE(37)] = 1660,
  [SMALL_STATE(38)] = 1693,
  [SMALL_STATE(39)] = 1726,
  [SMALL_STATE(40)] = 1757,
  [SMALL_STATE(41)] = 1802,
  [SMALL_STATE(42)] = 1833,
  [SMALL_STATE(43)] = 1864,
  [SMALL_STATE(44)] = 1907,
  [SMALL_STATE(45)] = 1940,
  [SMALL_STATE(46)] = 1981,
  [SMALL_STATE(47)] = 2012,
  [SMALL_STATE(48)] = 2043,
  [SMALL_STATE(49)] = 2092,
  [SMALL_STATE(50)] = 2125,
  [SMALL_STATE(51)] = 2176,
  [SMALL_STATE(52)] = 2213,
  [SMALL_STATE(53)] = 2248,
  [SMALL_STATE(54)] = 2279,
  [SMALL_STATE(55)] = 2312,
  [SMALL_STATE(56)] = 2343,
  [SMALL_STATE(57)] = 2374,
  [SMALL_STATE(58)] = 2423,
  [SMALL_STATE(59)] = 2448,
  [SMALL_STATE(60)] = 2473,
  [SMALL_STATE(61)] = 2498,
  [SMALL_STATE(62)] = 2520,
  [SMALL_STATE(63)] = 2531,
  [SMALL_STATE(64)] = 2542,
  [SMALL_STATE(65)] = 2553,
  [SMALL_STATE(66)] = 2566,
  [SMALL_STATE(67)] = 2576,
  [SMALL_STATE(68)] = 2586,
  [SMALL_STATE(69)] = 2596,
  [SMALL_STATE(70)] = 2606,
  [SMALL_STATE(71)] = 2616,
  [SMALL_STATE(72)] = 2626,
  [SMALL_STATE(73)] = 2636,
  [SMALL_STATE(74)] = 2646,
  [SMALL_STATE(75)] = 2654,
  [SMALL_STATE(76)] = 2662,
  [SMALL_STATE(77)] = 2672,
  [SMALL_STATE(78)] = 2682,
  [SMALL_STATE(79)] = 2690,
  [SMALL_STATE(80)] = 2698,
  [SMALL_STATE(81)] = 2708,
  [SMALL_STATE(82)] = 2718,
  [SMALL_STATE(83)] = 2728,
  [SMALL_STATE(84)] = 2738,
  [SMALL_STATE(85)] = 2745,
  [SMALL_STATE(86)] = 2752,
  [SMALL_STATE(87)] = 2759,
  [SMALL_STATE(88)] = 2766,
  [SMALL_STATE(89)] = 2771,
  [SMALL_STATE(90)] = 2778,
  [SMALL_STATE(91)] = 2783,
  [SMALL_STATE(92)] = 2788,
  [SMALL_STATE(93)] = 2793,
  [SMALL_STATE(94)] = 2800,
  [SMALL_STATE(95)] = 2805,
  [SMALL_STATE(96)] = 2809,
  [SMALL_STATE(97)] = 2813,
  [SMALL_STATE(98)] = 2817,
  [SMALL_STATE(99)] = 2821,
  [SMALL_STATE(100)] = 2825,
  [SMALL_STATE(101)] = 2829,
  [SMALL_STATE(102)] = 2833,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functiondef, 7, .production_id = 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functiondef, 7, .production_id = 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, .production_id = 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functiondef, 6, .production_id = 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functiondef, 6, .production_id = 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, .production_id = 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functiondef, 5, .production_id = 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functiondef, 5, .production_id = 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bindexpr, 5),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bindexpr, 5),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expr, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_functiondef, 4),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_functiondef, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bindexpr, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bindexpr, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_inner, 2),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_inner, 2), SHIFT_REPEAT(64),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_functiondef_repeat1, 2), SHIFT_REPEAT(93),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_functiondef_repeat1, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(61),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(22),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bind, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bindexpr_repeat1, 2), SHIFT_REPEAT(87),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bindexpr_repeat1, 2),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member, 1),
  [252] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fieldname, 3),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fieldname, 1),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jsonnet(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
